### PR TITLE
Fix store skipped checks results

### PR DESCRIPTION
**Pull request by patrick-levesque**
This PR fixes an issue with storing results using `EloquentHealthResultStore` for skipped checks when a frequency method such as `->everyFiveMinutes()` is used. The `ended_at` field is required and was not set for skipped checks. Also added `ResultStores` tests for skipped checks.

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks! Could you take a look at the failing tests?

**Comment by patrick-levesque** [comment]
"But it works on my computer." 😂  All tests pass locally and I didn't modify this failing test. After checking, I think it is possible that `DatabaseConnectionCountCheckTest` only gets 1 connection which fails the `expect($result->getNotificationMessage())` contains `connections` (plural). I will update this test to expect only `connection` and it should avoid this issue.

**Comment by patrick-levesque** [comment]
I had to merge recent commits with [Capitalize short summary for PingCheck](https://github.com/spatie/laravel-health/commit/14e7115e0fdf50a88547ff952ed8dfd5360984c9) to get all tests pass. 😅

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
