### PR TITLE
Make Check macroable and allow chaining callables in if() and unless()

### PR DESCRIPTION
**Pull request by oprypkhantc**
This would allow adding custom health checks filtering using macros:

```
Check::macro('inProduction', function () {
    return $this->if(fn () => app()->isProduction());
});

Check::macro('inContainerTypes', function (array $types) {
    return $this->if(fn () => in_array(app()->containerType(), $types));
});

Health::checks([
    DebugCheck::new()
        ->inProduction()
        ->inContainerTypes(['app']),
]);
```

### CODE REVIEW

**Comment by freekmurze** [comment]
Looks neat! Could you also write documentation for this?

**Comment by freekmurze** [comment]
Seems like the tests are also failing, could you take a look at that?

**Comment by oprypkhantc** [comment]
Sure thing :) I've fixed the tests and added documentation. I added a new `.md` docs page; it should appear in the docs by itself or do I need to add the page somewhere?

**Comment by freekmurze** [comment]
Thank you!

**Pull request merged**
