### PR TITLE
fix: correct return json

### PR DESCRIPTION
**Pull request by lxShaDoWxl**

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks! I don't see any benefits over the old code, so I'm going to leave it like it is.

**Comment by lxShaDoWxl** [comment]
Right now it doesn't work correctly and returns html instead of json
`Content-Type: text/html; charset=UTF-8`

**Comment by freekmurze** [comment]
Could you add a test that proves that the current behaviour is wrong, and make a minimal fix (maybe just set the correct header?)

**Comment by freekmurze** [comment]
Merged in another PR that will fix this.

Thanks for you work!

**Pull request closed without merging**
