### PR TITLE
Allow overriding the CheckFailedNotification class

### PR DESCRIPTION
**Pull request by moisish**
At the moment you can change the config file notifications.notifications but the class is harcoded on the RunHealthChecksCommand command and it's not possible to use your own

### CODE REVIEW

**Comment by freekmurze** [comment]
Using the first key seems a bit dirty to me. In the latest version, I've made it easy to override the notification class name to use.

**Comment by moisish** [comment]
Hello @freekmurze 
I can see you added a method getFailedNotificationClass but that means we need to override the RunHealthChecksCommand class. 
Why do we defined the class on the config file if you cannot change it in one place?

**Comment by moisish** [comment]
Another solution will be to change the config file and split the class and channels something like

```
'channels' => [
            'mail',
            'slack'
        ],
'notification' => Spatie\Health\Notifications\CheckFailedNotification::class

```

Let me know if this solution is acceptable and I will submit a new PR

**Comment by Nonslas** [comment]
I had same issue, should I make new command extend `RunHealthChecksCommand` to override method `getFailedNotificationClass`?

**Comment by moisish** [comment]
@freekmurze can we reopen this please?

**Pull request closed without merging**
