### PR TITLE
Add DatabaseSizeCheck

### PR DESCRIPTION
**Pull request by ralphjsmit**
This PR adds a new check called `DatabaseSizeCheck`. This check does what the name says – it fails when the size of the database reaches a certain threshold.

I decided to use GB as the order of magnitude instead of MB, since databases that are <1 GB usually aren't causing that much problems.

Thanks!

### CODE REVIEW

**Comment by freekmurze** [comment]
Very nice work, thank you!

However the tests are failing? Could you take a look at that?
Could you also rebase with `main` so the tests run against Laravel 10 as well?

**Comment by ralphjsmit** [comment]
Thanks! Updated to use `->selectOne()` instead of `->scalar()`, seems like scalar isn't available on L8.

**Comment by ralphjsmit** [comment]
Rebased on main, could you approve the tests run?

**Comment by ralphjsmit** [comment]
OK, could you give it another try? 🙂

**Comment by freekmurze** [comment]
We're all good, thanks again for this excellent PR!

**Comment by ralphjsmit** [comment]
Thanks ❤️

**Pull request merged**
