### PR TITLE
Improve redis memory usage check

### PR DESCRIPTION
**Pull request by pelmered**
Improvements:

- Added `->warnWhenAboveMb()` to set a warning threshold
- Sets memory usage  in summary and meta data

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks!

**Comment by pelmered** [comment]
@freekmurze I'll probably add similar improvements to some other of the checks. For example `DatabaseSizeCheck`. Should I make one PR per check or just one big PR?

**Comment by freekmurze** [comment]
I'd prefer separate PRs.

The new checks can go in packages of your own. Feel free to send a PR to our docs to add a link to them 👍

**Comment by pelmered** [comment]
Ok, great. I will do that!

**Pull request merged**
